# Generated by Django 3.0.5 on 2021-04-29 16:52

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosRed',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('tipo', models.IntegerField()),
                ('entrada', models.FloatField()),
                ('salida', models.FloatField()),
                ('createdAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ErroresSistema',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('mensaje', models.TextField()),
                ('moduloOiren', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
